[project]
name = "gitlab-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gitpython>=3.1.44",
    "mcp[cli]>=1.4.1",
    "python-gitlab>=5.6.0",
]
